### PR TITLE
Delete .azure-pipelines/Azure-PowerShell-Common-Publish.yml

### PR DESCRIPTION
**Pull request by YanaXu**
Remove unnecessary pipelines.

### CODE REVIEW

**Comment by isra-fel** [comment]
Can you point to the replacement of this pipeline before we remove it? Thanks @YanaXu

**Comment by YanaXu** [comment]
It's replaced by an internal Azure Pipeline whose yml is stored in Azure DevOps.

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
Need one more review @VeryEarly

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
